@api = http://localhost:3100/api/especies



###--------------------------------------------------------
### C
### Crear el nuevo registro de un sitio
POST {{api}}/createSitio
Content-Type: application/json

{
    "nombre": "Bajo Matador",
    "region": "Isla del Caño"
}

###-----------------------------------------------------------
### R 
### Retorna Todas las sitios registrados
{{api}}/getSitios


###--------------------------------------------------------
### C
### Crear el nuevo registro de una especie
POST {{api}}/createEspecie
Content-Type: application/json

{
    "familia": "Gobiidae",
    "nombre": "Lythrypnus cobalus",
    "cantidad":"20",
    "sitio": 4
}


###-----------------------------------------------------------
### R - ejemplo simple
### Retorna Todas las especies en la lista
{{api}}/getEspecies

###------------------------------------------------------------
### R - 
### Retorna especie con id especificado
{{api}}/getEspecieById/2


###------------------------------------------------------------
### R - 
### Retorna conteo total de observaciones
{{api}}/countObservaciones

###------------------------------------------------------------
### R - 
### Retorna lista ordenada por especie
{{api}}/getEspeciesSortByName

###------------------------------------------------------------
### R - 
### Retorna lista por familia
{{api}}/getEspeciesByFamily/Carcharhinidae


###-------------------------------------------------------------
### U
### update especie por Id
PUT {{api}}/updateEspecie/2
Content-Type: application/json

{
    "familia": "Haemulidae",
    "nombre": "Anisotremus interruptus",
    "cantidad": 10,
    "sitio": 2
}

###--------------------------------------------------------------
### D
### Borrar una especie por Id 
DELETE {{api}}/deleteEspecieById/11

### 